void _isr_00_wrapper();					//used to be void prefix keyword
void _isr_01_wrapper();
void _isr_02_wrapper();
void _isr_03_wrapper();
void _isr_04_wrapper();
void _isr_05_wrapper();
void _isr_06_wrapper();
void _isr_07_wrapper();
void _isr_08_wrapper();
void _isr_09_wrapper();
void _isr_0A_wrapper();
void _isr_0B_wrapper();
void _isr_0C_wrapper();
void _isr_0D_wrapper();
void _isr_0E_wrapper();
void _isr_0F_wrapper();
void _isr_10_wrapper();
void _isr_11_wrapper();
void _isr_12_wrapper();
void _isr_13_wrapper();
void _isr_14_wrapper();
void _isr_15_wrapper();
void _isr_16_wrapper();
void _isr_17_wrapper();
void _isr_18_wrapper();
void _isr_19_wrapper();
void _isr_1A_wrapper();
void _isr_1B_wrapper();
void _isr_1C_wrapper();
void _isr_1D_wrapper();
void _isr_1E_wrapper();
void _isr_1F_wrapper();
void _isr_20_wrapper();
void _isr_21_wrapper();
void _call_gate_wrapper();
extern  unsigned char exc_has_error[0x20];
extern unsigned short _exception_number;
extern unsigned short _exc_CS;
extern unsigned short _exc_IP;
